[project]
name = "ckanext-sdftheme"
version = "0.0.1"
description = "A design extension forata Facility's Data Cataolgue"
readme = "README.md"
authors = [
    {name = "Afia Akosah", email = "afia@opencitieslab.org"}
]
license = {text = "AGPL"}
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]

keywords = [ "CKAN", "theme,", "design,", "South", "Africa", ]
dependencies = []

[project.urls]
Homepage = "https://github.com/afia-ocl/ckanext-sdftheme"

[project.entry-points."ckan.plugins"]
sdftheme = "ckanext.sdftheme.plugin:SdfthemePlugin"


[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
filterwarnings = [
        "ignore::sqlalchemy.exc.SADeprecationWarning",
        "ignore::sqlalchemy.exc.SAWarning",
        "ignore::DeprecationWarning",
]
addopts = "--ckan-ini test.ini"
